name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, helmfile-runner]  # Target the runner with specific labels
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run a command
        run: echo "Running on Kubernetes-based GitHub Actions Runner!"
